# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Alex Handley"
resume_title:                   "Data Engineer"
resume_contact_email:           ""
resume_contact_telephone:       ""
resume_contact_address:         ""
resume_header_contact_info: ""
resume_header_intro: "
  <p>
  The majority of my career I have been a full stack developer working on a variety of projects from working with early stage startups on mobile apps to leading migrations of 90's Perl application into service oriented architectures for a multi national company.
  <br />
  Just over a year ago I got the opportunity to move into the Business Intelligence team at Wonderbly, this has been an amazing chance to work with and learn from analysts in the team. During this time I have enjoyed strengthening my analysis/data modelling skills and starting to develop new skills such as exploration using Machine Learning.
  <br />
  I would like my next role to allow me to continue getting exposure to the different aspects of the data science field by continuing to develop my skills in data modelling, machine learning and data engineering. I enjoy working in cross cutting teams with different skillsets to solve business problems.

  </p>
"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        ""

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/jglovier/resume-template"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
# resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
